title: "白龙的博客"
description: "bailong's blog powered by github-pages with jekyll theme"
url:
baseurl: ""
author: "白龙"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
